project:
  type: website

website:
  title: "Portfolio"
  site-url: "https://arjxn11.netlify.app"
  navbar:
    left:
      - href: index.qmd
        text: Home Page
      - text: Education and Experience
        href: exp.qmd
      - text: Projects
        menu:
          - text: Hedge Fund Simulation
            href: hedgefund.qmd
          - text: Project 2
            href: proj2.qmd
          - text: Project 3
            href: proj3.qmd
  page-footer:
    center: "Â© 2025 Arjun Singh"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual
